---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 10.01.2020 22:05
--
---Глобалки
TIMER_PERIOD = 0.03125
--wGeometry={}
do
	local InitGlobalsOrigin = InitGlobals -- записываем InitGlobals в переменную
	function InitGlobals()
		InitGlobalsOrigin() -- вызываем оригинальную InitGlobals из переменной
		InitGameCore()
	end
end

function InitGameCore()
	print("allOk")
	local hero=CreateUnit(Player(0), FourCC('H000'), GetPlayerStartLocationX(Player(0)), GetPlayerStartLocationY(Player(0)), 0)
	print(1)
	local Vector3 = wGeometry.Vector3
	--local c = Vector3:copyFromUnit(hero)
	print(2)
	local paladin = Vector3:copyFromUnit(hero)
	print(3)
	local speed = paladin:yawPitchOffset( 16.0, GetUnitFacing(hero) * ( math.pi / 180 ), 0.0 )
	print(4)
	local newPos = paladin:__add(speed)
	print(5)
	TimerStart(CreateTimer(), 0.1, true, function()
		--c:hermite(10, 0.5):applyToUnit(hero)
		SetUnitX( hero, newPos.x )
		SetUnitY( hero, newPos.y )
		print("t")
	end)
end